# Generated by Django 3.0.7 on 2020-06-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='tb_choi',
        ),
        migrations.AlterModelTable(
            name='question',
            table='tb_ques',
        ),
    ]
