# Generated by Django 3.0.7 on 2020-06-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200611_1834'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
