# Generated by Django 3.0.7 on 2020-06-24 03:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiel',
            new_name='Profile',
        ),
    ]
